version: '2' #版本号
services:
    lockzk1: #
        image: zookeeper:latest
        restart: always
        container_name: lockzk1
        ports:
            - "2181:2181"
        environment:
            ZOO_MY_ID: 1 #环境变量 这个id在集群必须是唯一的，该值介于1~255之间
            ZOO_SERVERS: server.1=lockzk1:2888:3888 server.2=lockzk2:2888:3888 server.3=lockzk3:2888:3888 #此变量允许您指定Zookeeper集群的计算机列表；
 
    lockzk2:
        image: zookeeper:latest
        restart: always
        container_name: lockzk2
        ports:
            - "2182:2181"
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=lockzk1:2888:3888 server.2=lockzk2:2888:3888 server.3=lockzk3:2888:3888
 
    lockzk3:
        image: zookeeper:latest
        restart: always
        container_name: lockzk3
        ports:
            - "2183:2181"
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=lockzk1:2888:3888 server.2=lockzk2:2888:3888 server.3=lockzk3:2888:3888
